version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./ :/code/
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
